### General ###
spring.application.name=JsonView

### Server ###
server.port=${APP_PORT_INTERNAL}

### Liquibase ###
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yml

### Datasource ###
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

### I hate jackson
### (i did not find any other adequate way to check that box using programmatic configurations (which had not been deprecated))
spring.jackson.mapper.default-view-inclusion=true